using System;

namespace XVNML.Core.Enums
{
    [Flags]
    public enum TokenType : long
    {
        Invalid = 0L,
        OpenBracket = 1L << 0,
        CloseBracket = 1L << 1,
        Comma = 1L << 2,
        Line = 1L << 3,
        OpenSquareBracket = 1L << 4,
        CloseSquareBracket = 1L << 5,
        Colon = 1L << 6,
        OpenCurlyBracket = 1L << 7,
        CloseCurlyBracket = 1L << 8,
        OpenParentheses = 1L << 9,
        CloseParentheses = 1L << 10,
        String = 1L << 11,
        Char = 1L << 12,
        Number = 1L << 13,
        ForwardSlash = 1L << 14,
        BackwardSlash = 1L << 15,
        Pound = 1L << 16,
        WhiteSpace = 1L << 17,
        Identifier = 1L << 18,
        EOF = 1L << 19,
        SingleLineComment = 1L << 20,
        MultilineComment = 1L << 21,
        DoubleColon = 1L << 22,
        EmptyString = 1L << 23,
        At = 1L << 24,
        Apostraphe = 1L << 25,
        DollarSign = 1L << 26,
        Exclamation = 1L << 27,
        Star = 1L << 28,
        Prompt = 1L << 39,
        Period = 1L << 30,
        SemiColon = 1L << 31,
        Equal = 1L << 32,
        Dash = 1L << 33,
        Ampersand = 1L << 34,
        Tilda = 1L << 35,
        InverseComma = 1L << 36,
        Percent = 1L << 37,
        Peak = 1L << 38,
        Plus = 1L << 49,
        Dialogue = 1L << 40,
        DoubleCloseBracket = 1L << 41,
        DoubleOpenBracket = 1L << 42,
        AnonymousCastSymbol = 1L << 43,
        Underscore = 1L << 44,
        ScopeBlock = 1L << 45
    }
}